env:
  global:
  - TERM=dumb
language: java
install: true
before_script:
- sudo apt update -y >/dev/null 2>&1 || true
- sudo apt install -y --no-install-recommends unzip tree >/dev/null 2>&1
script:
- export root=$(pwd)
- mkdir -p /tmp/{online,offline,simple-stupid}
# online
- cd $root/samples/online
- bash gradlew clean build
- unzip -d /tmp/online/client ./build/libs/online-client.jar
- unzip -d /tmp/online/full   ./build/libs/online.jar
# offline
- cd $root/samples/offline
- bash gradlew clean build
- unzip -d /tmp/offline/client ./build/libs/offline-client.jar
- unzip -d /tmp/offline/full   ./build/libs/offline.jar
# dump
- cd $root/samples/dump
- bash gradlew clean build
- unzip -d /tmp/simple-stupid/client ./build/libs/simple-stupid-client.jar
- unzip -d /tmp/simple-stupid/full   ./build/libs/simple-stupid.jar
